import Anthropic from '@anthropic-ai/sdk';
import pino from 'pino';
import { PageObject, PAGE_OBJECT_GENERATION_PROMPT } from '../types';

const logger = pino({ name: 'page-object-generator' });

/**
 * Generate Page Object Model class code
 */
export async function generatePageObjectCode(
  pageObject: PageObject,
  anthropicApiKey: string
): Promise<string> {
  logger.info('Generating page object code', { page_name: pageObject.name });

  try {
    const anthropic = new Anthropic({ apiKey: anthropicApiKey });

    const prompt = PAGE_OBJECT_GENERATION_PROMPT
      .replace('{page_name}', pageObject.name)
      .replace('{url}', pageObject.url)
      .replace('{selectors}', JSON.stringify(pageObject.selectors, null, 2));

    const response = await anthropic.messages.create({
      model: 'claude-3-haiku-20240307',
      max_tokens: 2048,
      messages: [{
        role: 'user',
        content: prompt
      }]
    });

    const content = response.content[0];
    if (content.type !== 'text') {
      throw new Error('Unexpected response type from Claude');
    }

    // Extract code from markdown if present
    let code = content.text.trim();
    if (code.startsWith('```typescript') || code.startsWith('```ts')) {
      code = code.replace(/^```(?:typescript|ts)\n?/, '').replace(/\n?```$/, '');
    } else if (code.startsWith('```')) {
      code = code.replace(/^```\n?/, '').replace(/\n?```$/, '');
    }

    logger.info('Successfully generated page object code', { page_name: pageObject.name });

    return code;
  } catch (error) {
    logger.error('Failed to generate page object code', { error, page_name: pageObject.name });

    // Fallback to template-based generation
    return generatePageObjectTemplate(pageObject);
  }
}

/**
 * Generate Page Object Model class using template (fallback)
 */
export function generatePageObjectTemplate(pageObject: PageObject): string {
  const className = `${pageObject.name}Page`;

  // Generate locator declarations
  const locators = Object.entries(pageObject.selectors)
    .map(([name, selector]) =>
      `  readonly ${name} = this.page.locator('${selector}');`
    )
    .join('\n');

  // Generate method implementations
  const methods = pageObject.methods.map(method => {
    const params = method.parameters?.join(': string, ') || '';
    const paramList = params ? `${params}: string` : '';

    return `  /**
   * ${method.description}
   */
  async ${method.name}(${paramList}) {
    // TODO: Implement ${method.name}
  }`;
  }).join('\n\n');

  const code = `import { Page, Locator } from '@playwright/test';

/**
 * Page Object Model for ${pageObject.name}
 * URL: ${pageObject.url}
 */
export class ${className} {
  readonly page: Page;

${locators}

  constructor(page: Page) {
    this.page = page;
  }

  /**
   * Navigate to this page
   */
  async goto() {
    await this.page.goto('${pageObject.url}');
  }

${methods}
}
`;

  return code;
}

/**
 * Generate all page object files
 */
export async function generatePageObjectFiles(
  pageObjects: PageObject[],
  anthropicApiKey: string,
  useAI: boolean = true
): Promise<Map<string, string>> {
  const files = new Map<string, string>();

  logger.info('Generating page object files', { count: pageObjects.length, use_ai: useAI });

  for (const pageObject of pageObjects) {
    const fileName = `${pageObject.name.toLowerCase()}.page.ts`;

    let code: string;
    if (useAI) {
      code = await generatePageObjectCode(pageObject, anthropicApiKey);
    } else {
      code = generatePageObjectTemplate(pageObject);
    }

    files.set(fileName, code);
  }

  logger.info('Generated page object files', { file_count: files.size });

  return files;
}

/**
 * Generate index file for page objects
 */
export function generatePageObjectsIndex(pageObjects: PageObject[]): string {
  const exports = pageObjects.map(po => {
    const className = `${po.name}Page`;
    const fileName = po.name.toLowerCase();
    return `export { ${className} } from './${fileName}.page';`;
  }).join('\n');

  return `/**
 * Page Object Models
 * Auto-generated by E2E Test Agent
 */

${exports}
`;
}
