#!/bin/bash

# Test Final: Production-Ready Hello World
# This script generates a production-ready full-stack app with all features

echo "================================================"
echo "Testing Final: Production-Ready Hello World"
echo "================================================"
echo ""
echo "Generating production app with:"
echo "- Full-stack hello world"
echo "- Authentication pattern (no JWT signing)"
echo "- Complete error handling"
echo "- Test setup included"
echo "- Production configurations"
echo "- Comprehensive documentation"
echo ""

# Generate the production-ready app
RESPONSE=$(curl -s -X POST http://localhost:3000/api/v1/workflows \
  -H "Content-Type: application/json" \
  -d '{
    "type": "fullstack",
    "name": "hello-world-production",
    "description": "Production-ready hello world app with full Zyp compliance",
    "priority": "high",
    "requirements": "Production-ready full-stack hello world application with all Zyp platform policies enforced. Frontend: React 19.2.0, Vite 6.0.11, TypeScript 5.4.5. Backend: Fastify 5.6.1, Prisma 5.14.0, Zod 3.23.0, TypeScript 5.4.5. Features: Authentication middleware that trusts x-user-id header and returns sessionPayload (NO JWT signing), comprehensive error handling with envelope pattern, request ID tracking, structured logging, health checks, graceful shutdown, connection pooling, test setup with Vitest. Database: PostgreSQL with isolated database per app. Include: docker-compose.yml, comprehensive README, API documentation, .env.example files. All dependencies must use exact versions (no ^ or ~). NO raw SQL, NO jsonwebtoken dependency, NO direct app-to-app communication."
  }')

echo "Response from orchestrator:"
echo "$RESPONSE" | jq '.' 2>/dev/null || echo "$RESPONSE"
echo ""

# Extract workflow ID
WORKFLOW_ID=$(echo "$RESPONSE" | jq -r '.id' 2>/dev/null)

if [ ! -z "$WORKFLOW_ID" ] && [ "$WORKFLOW_ID" != "null" ]; then
    echo "Workflow ID: $WORKFLOW_ID"
    echo ""
    echo "================================================"
    echo "Production Deployment Steps:"
    echo "================================================"
    echo ""
    echo "1. Navigate to app:"
    echo "   cd /tmp/agentic-sdlc-output/$WORKFLOW_ID/hello-world-production"
    echo ""
    echo "2. Review documentation:"
    echo "   cat README.md"
    echo ""
    echo "3. Configure environment:"
    echo "   cp backend/.env.example backend/.env"
    echo "   cp frontend/.env.example frontend/.env"
    echo ""
    echo "4. Start infrastructure:"
    echo "   docker-compose up -d"
    echo ""
    echo "5. Deploy backend:"
    echo "   cd backend"
    echo "   npm install"
    echo "   npm run db:migrate"
    echo "   npm run build"
    echo "   npm run start"
    echo ""
    echo "6. Deploy frontend:"
    echo "   cd ../frontend"
    echo "   npm install"
    echo "   npm run build"
    echo "   npm run preview"
    echo ""
    echo "7. Run tests:"
    echo "   cd ../backend && npm test"
    echo "   cd ../frontend && npm test"
    echo ""
    echo "================================================"
    echo "Production Validation Checklist:"
    echo "================================================"
    echo ""
    echo "Architecture Compliance:"
    echo "[ ] React 19.2.0, Vite 6.0.11 (exact versions)"
    echo "[ ] Fastify 5.6.1, Prisma 5.14.0, Zod 3.23.0 (exact)"
    echo "[ ] TypeScript 5.4.5 (exact)"
    echo "[ ] NO version ranges (^ or ~) in any package.json"
    echo ""
    echo "Security Compliance:"
    echo "[ ] NO JWT signing in app (returns sessionPayload)"
    echo "[ ] NO jsonwebtoken dependency"
    echo "[ ] Trusts x-user-id header from authenticated requests"
    echo "[ ] NO raw SQL (Prisma only)"
    echo ""
    echo "API Design:"
    echo "[ ] Envelope pattern on all responses"
    echo "[ ] Zod validation at all boundaries"
    echo "[ ] Proper error handling"
    echo "[ ] Request ID tracking"
    echo ""
    echo "Database:"
    echo "[ ] Isolated PostgreSQL database"
    echo "[ ] Migrations work correctly"
    echo "[ ] Connection pooling configured"
    echo ""
    echo "Production Features:"
    echo "[ ] Health check endpoint"
    echo "[ ] Graceful shutdown"
    echo "[ ] Structured logging"
    echo "[ ] Environment configuration"
    echo "[ ] Test suite included"
    echo "[ ] Documentation complete"
    echo ""
    echo "================================================"
    echo "Performance Tests:"
    echo "================================================"
    echo ""
    echo "# Health check:"
    echo "curl http://localhost:3000/api/health"
    echo ""
    echo "# API endpoint:"
    echo "curl http://localhost:3000/api/hello"
    echo ""
    echo "# With auth header:"
    echo "curl http://localhost:3000/api/hello \\"
    echo "  -H 'x-user-id: test-user-123'"
    echo ""
    echo "# Load test:"
    echo "for i in {1..100}; do"
    echo "  curl -s http://localhost:3000/api/hello > /dev/null &"
    echo "done"
    echo "wait"
else
    echo "Failed to extract workflow ID"
fi

echo ""
echo "================================================"
echo "Final production test submitted"
echo "================================================"